version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pymyq
    versions:
    - 3.0.1
    - 3.0.2
    - 3.0.3
  - dependency-name: environs
    versions:
    - 9.3.1
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
